name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 根据需要选择合适的Python版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 你的依赖应该在这个文件中定义

      # 运行测试并生成覆盖率报告
      - name: Run tests with pytest
        run: |
          pytest --cov=./  # 确保你的项目包含pytest和pytest-cov作为依赖

      # 上传覆盖率报告到 Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
